### PR TITLE
Merge upstream 2024-06-30 (qt6)

### PR DESCRIPTION
**Pull request by mnutt**
Upstream changes up to 2024-06-30.

Notable:
* More usage of `std::span`. Some of this has [broken automatic conversion between qt and webkit string types](https://github.com/movableink/webkit/commit/077a9ccc61af758033a1f1469d5a5fd88b1dd411#diff-7203473b7f3638630419fefec515da171f5633e5ea4dab9e7a8fb22b0a18444dL260-L261), and there is likely some cleanup work needed to ensure this is safe/performant
* Sync upstream changes to `texmap` to our vendored version
* This PR supersedes https://github.com/movableink/webkit/pull/40 so everything in that one as well.

### CODE REVIEW

**Comment by mnutt** [comment]
@chaplin89 sorry about that, I had hoped to get it done before I went on vacation but didn't quite get there.

You're totally right about GStreamer. It has unfortunately been broken for a while but was default-disabled in previous releases but now isn't. I looked at it for a few days and have a separate branch with it compiling with `USE_GSTREAMER=ON`, but videos aren't actually displaying yet. So I may disable in the build for now and continue working on that.

**Comment by chaplin89** [comment]
@mnutt thanks for the answer, no worries!

 I'm not much interested in gstreamer, I was wondering about that only because it was breaking the compilation and I was wondering if I was missing something.

Sorry I have another question, do you have any instructions to build this on windows? I'm interested in the project and I can potentially help with something. I was wondering how to build it on windows without much trial and error (if you are still supporting windows in your fork). Thank you!

**Comment by mnutt** [comment]
@chaplin89 unfortunately I don't really use windows so haven't been testing it there. I'd definitely contributions to get windows support working, though!

**Comment by mnutt** [comment]
I've disabled GStreamer support on Linux for the time being, in order to move things forward.

**Pull request merged**
